# Generated by Django 3.1.2 on 2022-04-05 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Group Description')),
                ('type', models.CharField(choices=[('PO', 'poll'), ('MS', 'mission'), ('EV', 'event')], default='PO', max_length=2)),
                ('voting_type', models.IntegerField(choices=[(0, 'condorcet'), (1, 'traffic'), (2, 'cardinal')], default=0)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='groups/polls/result/')),
                ('result_hash', models.TextField(blank=True, null=True)),
                ('result_token', models.TextField(blank=True, null=True)),
                ('top_proposal', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Request accepted time')),
                ('votes_counted', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('total_participants', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(verbose_name='Poll Comments')),
                ('edited', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='groups/polls/docs/')),
            ],
        ),
        migrations.CreateModel(
            name='PollProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('DEFAULT', 'Default'), ('DROP', 'Drop')], default='DEFAULT', max_length=30)),
                ('proposal', models.TextField()),
                ('final_score_positive', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('final_score_negative', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='groups/polls/proposal/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollProposalComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(verbose_name='Counter Proposal Comments')),
                ('edited', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollProposalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('DEFAULT', 'Default'), ('DROP', 'Drop')], default='DEFAULT', max_length=30)),
                ('proposal', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('final_score_positive', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('final_score_negative', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollProposalEventComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(verbose_name='Counter Proposal Comments')),
                ('edited', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollProposalEventIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('priority', models.DecimalField(decimal_places=10, max_digits=19)),
                ('is_positive', models.BooleanField()),
                ('hash', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollProposalEventThreads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollProposalIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('priority', models.DecimalField(decimal_places=10, max_digits=19)),
                ('is_positive', models.BooleanField()),
                ('hash', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollProposalThreads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollUserDelegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('vote_type', models.CharField(choices=[('upvote', 'Up vote'), ('downvote', 'Down vote')], max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_shown', models.BooleanField(db_index=True, default=True, verbose_name='Shown to user')),
                ('is_rejected', models.BooleanField(db_index=True, default=False, verbose_name='Is Rejected')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(verbose_name='Post Comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='polls.post')),
            ],
            options={
                'verbose_name': 'PostComment',
                'verbose_name_plural': 'Post Comments',
                'ordering': ('-created_at',),
            },
        ),
    ]
