# Generated by Django 3.1.2 on 2022-04-05 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('users', '0001_initial'),
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.group'),
        ),
        migrations.AddField(
            model_name='pollvotes',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
        migrations.AddField(
            model_name='pollvotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='polluserdelegate',
            name='delegator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegate_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='polluserdelegate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.group'),
        ),
        migrations.AddField(
            model_name='polluserdelegate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposalthreads',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_thread_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposalthreads',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_thread_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposalthreads',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='polls.pollproposalthreads', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='pollproposalthreads',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposal'),
        ),
        migrations.AddField(
            model_name='pollproposalthreads',
            name='score',
            field=models.ManyToManyField(related_name='proposal_thread_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposalindex',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposal'),
        ),
        migrations.AddField(
            model_name='pollproposalindex',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposaleventthreads',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_event_thread_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposaleventthreads',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_event_thread_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposaleventthreads',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='polls.pollproposaleventthreads', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='pollproposaleventthreads',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposalevent'),
        ),
        migrations.AddField(
            model_name='pollproposaleventthreads',
            name='score',
            field=models.ManyToManyField(related_name='proposal_event_thread_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposaleventindex',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposalevent'),
        ),
        migrations.AddField(
            model_name='pollproposaleventindex',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposaleventcomments',
            name='counter_proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposalevent'),
        ),
        migrations.AddField(
            model_name='pollproposaleventcomments',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_event_comment_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposaleventcomments',
            name='likes',
            field=models.ManyToManyField(related_name='proposal_event_comment_likes_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposaleventcomments',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_event_comment_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposaleventcomments',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposaleventcomments'),
        ),
        migrations.AddField(
            model_name='pollproposalevent',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
        migrations.AddField(
            model_name='pollproposalevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposalcomments',
            name='counter_proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposal'),
        ),
        migrations.AddField(
            model_name='pollproposalcomments',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_comment_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposalcomments',
            name='likes',
            field=models.ManyToManyField(related_name='proposal_comment_likes_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposalcomments',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_comment_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollproposalcomments',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposalcomments'),
        ),
        migrations.AddField(
            model_name='pollproposal',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
        migrations.AddField(
            model_name='pollproposal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollcomments',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollcomments',
            name='likes',
            field=models.ManyToManyField(related_name='likes_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollcomments',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollcomments',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
        migrations.AddField(
            model_name='pollcomments',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.pollcomments'),
        ),
        migrations.AddField(
            model_name='pollbookmark',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
        migrations.AddField(
            model_name='pollbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='poll_documents', to='polls.PollDocs'),
        ),
        migrations.AddField(
            model_name='poll',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.group'),
        ),
        migrations.AddField(
            model_name='poll',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='polluserdelegate',
            unique_together={('user', 'group', 'delegator')},
        ),
        migrations.AlterUniqueTogether(
            name='pollproposalindex',
            unique_together={('proposal', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='pollproposaleventindex',
            unique_together={('proposal', 'user', 'priority', 'is_positive', 'hash')},
        ),
        migrations.AlterUniqueTogether(
            name='pollproposalevent',
            unique_together={('poll', 'date')},
        ),
    ]
