# Generated by Django 3.1.2 on 2021-09-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollcounterproposal',
            name='type',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
