# Generated by Django 3.1.2 on 2021-09-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pollcounterproposal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('PO', 'Poll'), ('MS', 'Mission'), ('EV', 'Event')], default='PO', max_length=2),
        ),
    ]
