# Generated by Django 3.1.2 on 2021-09-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
