# Generated by Django 3.1.2 on 2021-10-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollcounterproposal',
            name='type',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('DROP', 'Drop')], default='DEFAULT', max_length=30),
        ),
    ]
