# Generated by Django 3.1.2 on 2021-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20211006_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
