# Generated by Django 3.1.2 on 2021-10-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_poll_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='data',
        ),
        migrations.AddField(
            model_name='poll',
            name='top_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='top_proposal', to='polls.pollcounterproposal'),
        ),
    ]
