# Generated by Django 3.1.2 on 2021-10-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20211011_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollcounterproposal',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
