# Generated by Django 3.1.2 on 2021-10-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_pollcounterproposal_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollcounterproposal',
            old_name='data',
            new_name='val',
        ),
    ]
