# Generated by Django 3.1.2 on 2021-10-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20211013_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollcounterproposal',
            name='val',
        ),
        migrations.CreateModel(
            name='PollCounterProposalEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('counter_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollcounterproposal')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
            ],
            options={
                'unique_together': {('poll', 'date')},
            },
        ),
    ]
