# Generated by Django 3.1.2 on 2021-10-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20211014_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollCounterProposalEvents',
            new_name='PollCounterProposalEvent',
        ),
    ]
