# Generated by Django 3.1.2 on 2021-10-14 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0013_auto_20211014_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollcounterproposalevent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='groups/polls/proposal/'),
        ),
        migrations.AddField(
            model_name='pollcounterproposalevent',
            name='final_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollcounterproposalevent',
            name='proposal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollcounterproposalevent',
            name='type',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('DROP', 'Drop')], default='DEFAULT', max_length=30),
        ),
        migrations.AddField(
            model_name='pollcounterproposalevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pollcounterproposalevent',
            unique_together={('poll', 'date'), ('poll', 'user')},
        ),
        migrations.RemoveField(
            model_name='pollcounterproposalevent',
            name='counter_proposal',
        ),
    ]
