# Generated by Django 3.1.2 on 2021-10-14 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0014_auto_20211014_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollProposalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('DEFAULT', 'Default'), ('DROP', 'Drop')], default='DEFAULT', max_length=30)),
                ('proposal', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('poll', 'date'), ('poll', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='PollCounterProposalEvent',
        ),
    ]
