# Generated by Django 3.1.2 on 2021-10-15 16:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0015_auto_20211014_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollCounterProposal',
            new_name='PollProposal',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='top_proposal',
        ),
    ]
