# Generated by Django 3.1.2 on 2021-10-15 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20211015_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='top_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poll_top_proposal', to='polls.pollproposal'),
        ),
    ]
