# Generated by Django 3.1.2 on 2021-10-18 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0017_poll_top_proposal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollCounterProposalsIndex',
            new_name='PollProposalEventIndex',
        ),
        migrations.AlterField(
            model_name='pollproposaleventindex',
            name='counter_proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposalevent'),
        ),
        migrations.CreateModel(
            name='PollProposalIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField()),
                ('is_positive', models.BooleanField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('proposal', 'user', 'priority', 'is_positive')},
            },
        ),
    ]
