# Generated by Django 3.1.2 on 2021-10-18 22:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0018_auto_20211018_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollproposaleventindex',
            old_name='counter_proposal',
            new_name='proposal',
        ),
        migrations.AlterUniqueTogether(
            name='pollproposaleventindex',
            unique_together={('proposal', 'user', 'priority', 'is_positive')},
        ),
    ]
