# Generated by Django 3.1.2 on 2021-10-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20211018_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollproposaleventindex',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposalevent'),
        ),
    ]
