# Generated by Django 3.1.2 on 2021-10-25 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0021_auto_20211018_2204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollproposalindex',
            unique_together={('proposal', 'user')},
        ),
        migrations.CreateModel(
            name='PollProposalThreads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_comment_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_comment_modified_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='polls.pollproposalthreads', verbose_name='parent')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposal')),
                ('score', models.ManyToManyField(related_name='proposal_comment_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
