# Generated by Django 3.1.2 on 2021-10-29 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0022_auto_20211025_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
