# Generated by Django 3.1.2 on 2021-10-29 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0023_poll_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='subscribers',
            field=models.ManyToManyField(related_name='poll_subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
