# Generated by Django 3.1.2 on 2021-11-19 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20211029_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='subscribers',
        ),
    ]
