# Generated by Django 3.1.2 on 2021-12-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_remove_poll_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='poll_documents', to='polls.PollDocs'),
        ),
    ]
