# Generated by Django 3.1.2 on 2021-12-17 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0026_auto_20211214_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollProposalComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(verbose_name='Counter Proposal Comments')),
                ('edited', models.BooleanField(default=False)),
                ('counter_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_comment_created_by', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='proposal_comment_likes_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_comment_modified_by', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposalcomments')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollProposalEventComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(verbose_name='Counter Proposal Comments')),
                ('edited', models.BooleanField(default=False)),
                ('counter_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_event_comment_created_by', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='proposal_event_comment_likes_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_event_comment_modified_by', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposaleventcomments')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollProposalEventThreads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_event_thread_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_event_thread_modified_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='polls.pollproposaleventthreads', verbose_name='parent')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposal')),
                ('score', models.ManyToManyField(related_name='proposal_event_thread_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='pollproposalthreads',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_thread_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pollproposalthreads',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_thread_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pollproposalthreads',
            name='score',
            field=models.ManyToManyField(related_name='proposal_thread_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PollCounterProposalComments',
        ),
    ]
