# Generated by Django 3.1.2 on 2021-12-17 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20211217_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollproposaleventcomments',
            name='counter_proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposalevent'),
        ),
        migrations.AlterField(
            model_name='pollproposaleventthreads',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollproposalevent'),
        ),
    ]
