# Generated by Django 3.1.2 on 2022-01-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20211217_1637'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollproposal',
            unique_together=set(),
        ),
    ]
