# Generated by Django 3.1.2 on 2022-01-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20220106_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='voting_type',
            field=models.IntegerField(choices=[('0', 'condorcet'), ('1', 'traffic')], default='0'),
        ),
    ]
