# Generated by Django 3.1.2 on 2022-01-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_poll_voting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='voting_type',
            field=models.IntegerField(choices=[('condorcet', 'Condorcet'), ('traffic', 'Traffic')], default='condorcet'),
        ),
    ]
