# Generated by Django 3.1.2 on 2022-01-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_auto_20220113_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='voting_type',
            field=models.TextField(choices=[('condorcet', 'Condorcet'), ('traffic', 'Traffic')], default='condorcet'),
        ),
    ]
