# Generated by Django 3.1.2 on 2022-01-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20220113_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='voting_type',
            field=models.IntegerField(choices=[('0', 'condorcet'), ('1', 'traffic')], default='0'),
        ),
    ]
