# Generated by Django 3.1.2 on 2022-01-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20220113_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollproposal',
            old_name='final_score',
            new_name='final_score_positive',
        ),
        migrations.RenameField(
            model_name='pollproposalevent',
            old_name='final_score',
            new_name='final_score_positive',
        ),
        migrations.AddField(
            model_name='poll',
            name='total_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollproposal',
            name='final_score_negative',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollproposalevent',
            name='final_score_negative',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='top_proposal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='voting_type',
            field=models.IntegerField(choices=[(0, 'condorcet'), (1, 'traffic')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='pollproposalevent',
            unique_together={('poll', 'date')},
        ),
    ]
