# Generated by Django 3.1.2 on 2022-02-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_auto_20220119_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='voting_type',
            field=models.IntegerField(choices=[(0, 'condorcet'), (1, 'traffic'), (2, 'cardinal')], default=0),
        ),
    ]
