# Generated by Django 3.1.2 on 2022-02-14 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0035_auto_20220202_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollproposaleventindex',
            name='hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollproposalindex',
            name='hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pollproposaleventindex',
            unique_together={('proposal', 'user', 'priority', 'is_positive', 'hash')},
        ),
    ]
