# Generated by Django 3.1.2 on 2022-02-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_auto_20220214_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='groups/polls/results/'),
        ),
        migrations.AddField(
            model_name='poll',
            name='result_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='result_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pollproposal',
            name='final_score_negative',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='pollproposal',
            name='final_score_positive',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='pollproposalevent',
            name='final_score_negative',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='pollproposalevent',
            name='final_score_positive',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='pollproposaleventindex',
            name='priority',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='pollproposalindex',
            name='priority',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
