# Generated by Django 3.1.2 on 2022-02-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_auto_20220222_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='groups/polls/result/'),
        ),
    ]
