# Generated by Django 3.1.2 on 2021-10-29 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_groupchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subscribers',
            field=models.ManyToManyField(related_name='group_subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
