# Generated by Django 3.1.2 on 2021-11-19 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_group_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='subscribers',
        ),
    ]
