# Generated by Django 3.1.2 on 2022-01-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_groupmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembers',
            name='allow_vote',
            field=models.BooleanField(default=False),
        ),
    ]
