# Generated by Django 3.1.2 on 2022-01-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_groupmembers_allow_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembers',
            name='allow_vote',
            field=models.BooleanField(default=True),
        ),
    ]
