# Generated by Django 3.1.2 on 2022-02-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20220119_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='blockchain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='allow_vote',
            field=models.BooleanField(default=False),
        ),
    ]
