# Generated by Django 4.2.7 on 2024-11-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_scheduleevent_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
