# Generated by Django 4.2.16 on 2024-12-30 11:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('schedule', '0006_remove_scheduleevent_repeat_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleevent',
            name='repeat_next_run',
        ),
        migrations.RemoveField(
            model_name='scheduleevent',
            name='repeat_task',
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='reminders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=10),
        ),
        migrations.CreateModel(
            name='ScheduleEventReminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleevent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='reminder_tasks',
            field=models.ManyToManyField(to='schedule.scheduleeventreminders'),
        ),
    ]
