# Generated by Django 4.2.16 on 2024-12-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('schedule', '0007_remove_scheduleevent_repeat_next_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='reminder_tasks',
            field=models.ManyToManyField(to='django_celery_beat.periodictask'),
        ),
    ]
