# Generated by Django 4.2.16 on 2024-12-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_scheduleevent_reminder_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleEventReminders',
        ),
    ]
