# Generated by Django 4.2.17 on 2025-08-26 11:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_delete_scheduleeventreminders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleevent',
            name='reminder_tasks',
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='reminders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=10),
        ),
    ]
