# Generated by Django 4.2.17 on 2025-10-21 16:23

from django.conf import settings
from django.db import migrations
from numpy.core.defchararray import startswith


# Populates the content_type fields for Schedule and ScheduleEvent
def migrate_schedule_origins(apps, schema_editor):
    Schedule = apps.get_model('schedule', 'Schedule')
    ScheduleEvent = apps.get_model('schedule', 'ScheduleEvent')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get ContentType instances for each model
    try:
        origins = {
            'user': ContentType.objects.get(app_label='user', model='user'),
            'group': ContentType.objects.get(app_label='group', model='group'),
            'group_poll': ContentType.objects.get(app_label='poll', model='poll'),
            'group_poll_proposal': ContentType.objects.get(app_label='poll', model='pollproposal'),
        }

    except ContentType.DoesNotExist:
        return

    # Populate schedule content_type with origin fields
    for schedule in Schedule.objects.all():
        if not schedule.content_type:
            schedule.content_type = origins[schedule.origin_name]
            schedule.object_id = schedule.origin_id
            schedule.save()

    # Populate schedule event content_type with origin fields
    for event in ScheduleEvent.objects.all():
        if not startswith(event.title, 'group_poll_'):
            event.content_type = origins[event.origin_name]
            event.object_id = event.origin_id
            event.save()

        else:
            event.content_type = ContentType.objects.get(app_label='poll', model='poll')
            event.object_id = event.origin_id
            event.save()


def populate_schedule_tags(apps, schema_editor):
    Schedule = apps.get_model('schedule', 'Schedule')
    ScheduleTag = apps.get_model('schedule', 'ScheduleTag')

    for schedule in Schedule.objects.all():
        schedule_tag = ScheduleTag.objects.create(name='default', schedule_id=schedule.id)
        schedule.default_tag = schedule_tag
        schedule.save()


def migrate_from_schedule_subscription_to_user_subscription(apps, schema_editor):
    ScheduleSubscription = apps.get_model('schedule', 'ScheduleSubscription')
    ScheduleEvent = apps.get_model('schedule', 'ScheduleEvent')
    Schedule = apps.get_model('schedule', 'Schedule')
    User = apps.get_model('user', 'User')
    Group = apps.get_model('group', 'Group')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    WorkGroup = apps.get_model('group', 'WorkGroup')

    # TODO keep previous schedule events intact
    ScheduleSubscription.objects.all().delete()

    # Create new user subscriptions
    for user in User.objects.all():
        schedule = user.schedule
        if not schedule:
            schedule = Schedule.objects.create(content_type=ContentType.objects.get(app_label='user', model='user'),
                                               object_id=user.id,
                                               origin_id=user.id,
                                               origin_name='user')

        ScheduleSubscription.objects.create(user=user, schedule_id=schedule.id)

    # Create new group subscriptions
    for group in Group.objects.all():
        schedule = Schedule.objects.get(origin_name='group', origin_id=group.id)
        schedule.content_type = ContentType.objects.get(app_label='group', model='group')
        schedule.object_id = group.id
        schedule.save()

        for group_user in group.groupuser_set.filter(active=True).all():
            ScheduleSubscription.objects.create(user=group_user.user, schedule_id=schedule.id)

        # Work groups as well
        for work_group in group.workgroup_set.all():
            wg_schedule = Schedule.objects.get(origin_name='workgroup', origin_id=work_group.id)
            for schedule_event in schedule.scheduleevent_set.filter(work_group__isnull=False).all():
                schedule_event.update(created_by=work_group)

            for workgroup_user in work_group.workgroupuser_set.filter(active=True).all():
                ScheduleSubscription.objects.create(user=workgroup_user.group_user.user, schedule_id=wg_schedule.id)



class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0011_scheduletag_schedule_content_type_schedule_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulesubscription',
            name='target'
        ),
        migrations.RunPython(migrate_schedule_origins),
        migrations.RunPython(populate_schedule_tags),
        migrations.RunPython(migrate_from_schedule_subscription_to_user_subscription)
    ]
