# Generated by Django 4.2.17 on 2026-02-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_alter_scheduleevent_description_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scheduletag',
            constraint=models.UniqueConstraint(fields=('schedule', 'name'), name='scheduleuniquenameconstraint'),
        ),
    ]
