# Generated by Django 4.2.17 on 2026-03-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_scheduletag_scheduleuniquenameconstraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='repeat_frequency_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='scheduleeventsubscription',
            constraint=models.UniqueConstraint(models.F('event'), models.F('schedule_user'), name='eventscheduleuser_unique'),
        ),
    ]
