# Generated by Django 4.0.8 on 2023-02-13 15:30

from django.db import migrations, models
import django.db.models.deletion


def pre_populate_fields(apps, schema_editor):
    User = apps.get_model('user', 'user')
    Schedule = apps.get_model('schedule', 'schedule')
    for user in User.objects.all():
        schedule = Schedule.objects.create(name=user.username, origin_name='user', origin_id=user.id)
        user.schedule_id = schedule.id
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
            preserve_default=False,
        ),
        migrations.RunPython(pre_populate_fields),
        migrations.AlterField(
            model_name='user',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')
        )
    ]
