# Generated by Django 4.0.3 on 2022-03-15 16:48

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardUser',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=120)),
                ('username', models.CharField(max_length=120, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('verification_code', models.UUIDField(default=uuid.UUID('e5b5952f-bfe4-4cf9-bccd-98b9afcd5dae'), editable=False, primary_key=True, serialize=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
