# Generated by Django 4.0.3 on 2022-03-15 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_onboarduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarduser',
            name='verification_code',
            field=models.UUIDField(default=uuid.UUID('0ae5b1cd-b644-4fdb-9cef-f94dd986b4dc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
