# Generated by Django 4.0.8 on 2023-02-15 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('user', '0002_user_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.schedule'),
        ),
    ]
