# Generated by Django 4.0.8 on 2023-02-15 15:51

from django.db import migrations, models
import django.db.models.deletion


def pre_populate_fields(apps, schema_editor):
    User = apps.get_model('user', 'user')
    Schedule = apps.get_model('schedule', 'schedule')
    for user in User.objects.all():
        schedule = Schedule.objects.create(name=user.username, origin_name='user', origin_id=user.id)
        user.schedule_id = schedule.id
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('user', '0002_user_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.schedule'),
        ),
    ]
