# Generated by Django 4.0.8 on 2023-02-23 15:37

from django.db import migrations, models
import django.db.models.deletion


def pre_populate_fields():


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_kanban_alter_kanbanentry_assignee_and_more'),
        ('user', '0003_alter_user_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kanban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanban.kanban'),
        ),
        migrations.RunPython(pre_populate_fields)
    ]
