# Generated by Django 4.0.3 on 2022-03-16 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_onboarduser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarduser',
            name='verification_code',
            field=models.UUIDField(default=uuid.UUID('9f2c6b75-1551-400d-87a4-dbac9d73d3fa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
