# Generated by Django 4.0.8 on 2023-02-23 15:37

from django.db import migrations, models
import django.db.models.deletion


def pre_populate_fields(apps, schema_editor):
    User = apps.get_model('user', 'user')
    Kanban = apps.get_model('kanban', 'kanban')
    Schedule = apps.get_model('schedule', 'schedule')
    for user in User.objects.all():
        user.kanban = Kanban.objects.get(origin_type='user', origin_id=user.id)
        user.schedule = Schedule.objects.get(origin_name='user', origin_id=user.id)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_kanban'),
    ]

    operations = [
        migrations.RunPython(pre_populate_fields)
    ]
