# Generated by Django 4.0.3 on 2022-03-16 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_onboarduser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarduser',
            name='verification_code',
            field=models.UUIDField(default=uuid.UUID('8c93cb1a-c5aa-4d47-9b13-c4de40b207d9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
