# Generated by Django 4.0.3 on 2022-03-16 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_onboarduser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarduser',
            name='verification_code',
            field=models.UUIDField(default=uuid.UUID('ffece4e9-5891-4590-9308-5bdc4b1a2237'), editable=False, primary_key=True, serialize=False),
        ),
    ]
