# Generated by Django 4.0.3 on 2022-03-16 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_onboarduser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarduser',
            name='verification_code',
            field=models.UUIDField(default=uuid.UUID('4d96a59e-b4cb-4168-a4fc-fb64df0614a1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
