# Generated by Django 4.0.8 on 2023-06-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_theme',
            field=models.BooleanField(default=False),
        ),
    ]
