# Generated by Django 4.0.3 on 2022-03-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_onboarduser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarduser',
            name='verification_code',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
