# Generated by Django 4.2.7 on 2024-11-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_contact_email_user_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
