# Generated by Django 4.2.16 on 2025-03-08 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_messagechannel_users'),
        ('user', '0010_user_user_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direct_message',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserChatInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rejected', models.BooleanField(default=False)),
                ('message_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.messagechannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
