# Generated by Django 4.0.3 on 2022-07-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_passwordreset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
