# Generated by Django 4.2.16 on 2025-03-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_messagechannel_users'),
        ('user', '0011_user_direct_message_userchatinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatinvite',
            name='rejected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userchatinvite',
            unique_together={('user', 'message_channel')},
        ),
    ]
