# Generated by Django 4.2.16 on 2025-03-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_userchatinvite_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_status',
            field=models.CharField(choices=[('public', 'Public'), ('group_only', 'Group Only'), ('private', 'Private')], default='private'),
        ),
    ]
