# Generated by Django 4.2.16 on 2025-03-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_public_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_status',
            field=models.CharField(choices=[('public', 'Public'), ('group_only', 'Group Only'), ('private', 'Private')], default='private'),
        ),
    ]
