# Generated by Django 4.2.16 on 2025-03-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_chat_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchatinvite',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userchatinvite',
            constraint=models.UniqueConstraint(fields=('user', 'message_channel'), name='unique_user_invite'),
        ),
    ]
