# Generated by Django 4.2.16 on 2025-08-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_report_group_id_report_post_id_report_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='post_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='post_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
