# Generated by Django 4.2.17 on 2025-08-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_ensure_user_notification_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboarduser',
            name='username',
        ),
    ]
