# Generated by Django 4.2 on 2025-09-16 13:46

from django.db import migrations


def delete_all_onboard_users(apps, schema_editor):
    """
    Delete all OnboardUser instances from the database
    """
    OnboardUser = apps.get_model('user', 'OnboardUser')
    OnboardUser.objects.all().delete()


def reverse_delete_all_onboard_users(apps, schema_editor):
    """
    This migration is irreversible as we cannot restore deleted data
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_onboarduser_username'),
    ]

    operations = [
        migrations.RunPython(
            delete_all_onboard_users,
            reverse_delete_all_onboard_users,
        ),
    ]