# Generated by Django 4.2.16 on 2025-08-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_report_post_description_report_post_title'),
        ('user', '0019_remove_onboarduser_username'),
    ]

    operations = [
    ]
