# Generated by Django 4.2.17 on 2025-09-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_delete_all_onboard_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarduser',
            name='email',
            field=models.EmailField(max_length=120, unique=True),
        ),
    ]
