# Generated by Django 4.2 on 2025-09-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_onboarduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnboardUser',
        ),
    ]