# Generated by Django 4.2.17 on 2025-10-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_merge_20250829_1406'),
        ('user', '0025_onboarduser'),
    ]

    operations = [
    ]
