# Generated by Django 4.2.17 on 2026-03-13 11:57

import django.contrib.auth.validators
from django.db import migrations, models
import flowback.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_userbookmark_userbookmark_unique_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), flowback.common.validators.FieldNotBlankValidator]),
        ),
    ]
