"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
import environ
from pathlib import Path


env = environ.Env(DEBUG=(bool, False),
                  SECURE_PROXY_SSL_HEADERS=(bool, False),
                  DJANGO_SECRET=str,
                  FLOWBACK_URL=(str, None),
                  INSTANCE_NAME=(str, 'Flowback'),
                  PG_SERVICE=(str, 'flowback'),
                  REDIS_IP=(str, 'localhost'),
                  REDIS_PORT=(str, '6379'),
                  RABBITMQ_BROKER_URL=str,
                  URL_SUBPATH=(str, ''),
                  DISABLE_DEFAULT_USER_REGISTRATION=(bool, False),
                  FLOWBACK_DEFAULT_GROUP_JOIN=(str, None),
                  FLOWBACK_ALLOW_GROUP_CREATION=(bool, True),
                  FLOWBACK_GROUP_ADMIN_USER_LIST_ACCESS_ONLY=(bool, False),
                  FLOWBACK_DEFAULT_PERMISSION=(str, 'rest_framework.permissions.IsAuthenticated'),
                  EMAIL_HOST=(str, None),
                  EMAIL_SENDER=(str, None),
                  EMAIL_PORT=(str, None),
                  EMAIL_FROM=(str, None),
                  EMAIL_HOST_USER=(str, None),
                  EMAIL_HOST_PASSWORD=(str, None),
                  EMAIL_USE_TLS=(bool, None),
                  EMAIL_USE_SSL=(bool, None),
                  INTEGRATIONS=(list, []),
                  SCORE_VOTE_CEILING=(int, None),
                  SCORE_VOTE_FLOOR=(int, None)
                  )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

FLOWBACK_URL = env('FLOWBACK_URL')
INSTANCE_NAME = env('INSTANCE_NAME')
PG_SERVICE = env('PG_SERVICE')

ALLOWED_HOSTS = [FLOWBACK_URL or "*"]

CORS_ALLOW_ALL_ORIGINS = not bool(FLOWBACK_URL)
if not CORS_ALLOW_ALL_ORIGINS:
    if env('SECURE_PROXY_SSL_HEADERS'):
        CORS_ALLOWED_ORIGINS = [f'https://{FLOWBACK_URL}', f'wss://{FLOWBACK_URL}']
    else:
        CORS_ALLOWED_ORIGINS = [f'http://{FLOWBACK_URL}', f'ws://{FLOWBACK_URL}']

if env('SECURE_PROXY_SSL_HEADERS'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

URL_SUBPATH = env('URL_SUBPATH')

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_extensions',
    'rest_framework.authtoken',
    'django_celery_beat',
    'pgtrigger',
    'flowback.user',
    'flowback.group',
    'flowback.poll',
    'flowback.chat',
    'flowback.kanban',
    'flowback.notification',
    'flowback.comment',
    'flowback.schedule',
    'drf_spectacular'
] + env('INTEGRATIONS')

CELERY_BROKER_URL = env('RABBITMQ_BROKER_URL')

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'flowback.common.documentation.CustomAutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': (
        env('FLOWBACK_DEFAULT_PERMISSION'),
    ),
    'EXCEPTION_HANDLER': 'flowback.common.exception_handlers.drf_default_with_modifications_exception_handler'
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Flowback API',
    'DESCRIPTION': 'Documentation for interfacing with Flowback',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

AUTH_USER_MODEL = 'user.User'
DISABLE_DEFAULT_USER_REGISTRATION = env('DISABLE_DEFAULT_USER_REGISTRATION')

if data := env('FLOWBACK_DEFAULT_GROUP_JOIN'):
    FLOWBACK_DEFAULT_GROUP_JOIN = [int(i) for i in env('FLOWBACK_DEFAULT_GROUP_JOIN').split(',')]

else:
    FLOWBACK_DEFAULT_GROUP_JOIN = []

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

MEDIA_ROOT = str(BASE_DIR) + '/media'
MEDIA_URL = '/media/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

ASGI_APPLICATION = "backend.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(env('REDIS_IP'), env('REDIS_PORT'))],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'OPTIONS': {
            'service': PG_SERVICE,
            'passfile': '.flowback_pgpass',
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_SENDER = env('EMAIL_SENDER') or EMAIL_HOST
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = env('EMAIL_USE_TLS') or True
EMAIL_USE_SSL = env('EMAIL_USE_SSL') or False
DEFAULT_FROM_EMAIL = env('EMAIL_FROM', default=env('EMAIL_HOST_USER'))


# Poll related settings
SCORE_VOTE_CEILING = env('SCORE_VOTE_CEILING')
SCORE_VOTE_FLOOR = env('SCORE_VOTE_FLOOR')


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
