from backend.settings import (DEBUG,
                              FLOWBACK_KANBAN_LANES,
                              FLOWBACK_ALLOW_GROUP_CREATION,
                              FLOWBACK_ALLOW_DYNAMIC_POLL,
                              FLOWBACK_GROUP_ADMIN_USER_LIST_ACCESS_ONLY,
                              FLOWBACK_DEFAULT_GROUP_JOIN,
                              FLOWBACK_DISABLE_DEFAULT_USER_REGISTRATION,
                              )


def get_public_config():
    data = dict(
        DEBUG=DEBUG,
        FLOWBACK_KANBAN_LANES=FLOWBACK_KANBAN_LANES,
        FLOWBACK_ALLOW_GROUP_CREATION=FLOWBACK_ALLOW_GROUP_CREATION,
        FLOWBACK_ALLOW_DYNAMIC_POLL=FLOWBACK_ALLOW_DYNAMIC_POLL,
        FLOWBACK_GROUP_ADMIN_USER_LIST_ACCESS_ONLY=FLOWBACK_GROUP_ADMIN_USER_LIST_ACCESS_ONLY,
        FLOWBACK_DEFAULT_GROUP_JOIN=FLOWBACK_DEFAULT_GROUP_JOIN,
        FLOWBACK_DISABLE_DEFAULT_USER_REGISTRATION=FLOWBACK_DISABLE_DEFAULT_USER_REGISTRATION
    )

    return data