# Generated by Django 3.1.2 on 2022-04-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probability', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='probabilityvote',
            old_name='vote',
            new_name='score',
        ),
    ]
