# Generated by Django 3.1.2 on 2022-07-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probability', '0002_auto_20220412_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='probabilitypost',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
