# Generated by Django 3.1.2 on 2022-07-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probability', '0003_probabilitypost_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probabilitypost',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
