# Generated by Django 4.0.8 on 2022-11-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='poll',
            name='nowgreaterthanstartdate_check',
        ),
    ]
