# Generated by Django 4.0.3 on 2022-10-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.IntegerField(choices=[(1, 'ranking')]),
        ),
    ]
