# Generated by Django 4.0.3 on 2022-10-05 16:30

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_poll_poll_type'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='pollvotingtyperanking',
            name='protects_author_or_author_delegate',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pollvotingtyperanking',
            trigger=pgtrigger.compiler.Trigger(name='protects_author_or_author_delegate', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN ((NEW."author_id" IS NULL AND NEW."author_delegate_id" IS NULL) OR (NEW."author_id" IS NOT NULL AND NEW."author_delegate_id" IS NOT NULL))', func="RAISE EXCEPTION 'pgtrigger: Cannot insert or update rows from % table', TG_TABLE_NAME;", hash='b475740f10a35f5a575603f5bc855550b0888c29', operation='INSERT OR UPDATE', pgid='pgtrigger_protects_author_or_author_delegate_c765f', table='poll_pollvotingtyperanking', when='BEFORE')),
        ),
    ]
