# Generated by Django 4.0.3 on 2022-10-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_remove_pollvotingtyperanking_protects_author_or_author_delegate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='live_count',
            new_name='participants',
        ),
    ]
