# Generated by Django 4.0.8 on 2022-10-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_rename_live_count_poll_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
