# Generated by Django 4.0.8 on 2022-10-29 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_poll_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.IntegerField(choices=[(1, 'ranking'), (2, 'for_against'), (3, 'schedule')]),
        ),
        migrations.CreateModel(
            name='PollProposalTypeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poll.pollproposal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollVotingTypeForAgainst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote', models.BooleanField()),
                ('score', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.pollvoting')),
                ('author_delegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.polldelegatevoting')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.pollproposal')),
            ],
            options={
                'unique_together': {('author', 'proposal'), ('author_delegate', 'proposal')},
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pollvotingtypeforagainst',
            trigger=pgtrigger.compiler.Trigger(name='protects_author_or_author_delegate', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN ((NEW."author_id" IS NULL AND NEW."author_delegate_id" IS NULL) OR (NEW."author_id" IS NOT NULL AND NEW."author_delegate_id" IS NOT NULL))', func="RAISE EXCEPTION 'pgtrigger: Cannot insert or update rows from % table', TG_TABLE_NAME;", hash='20d230b97a5408ec7601f37319a875065a0b826a', operation='INSERT OR UPDATE', pgid='pgtrigger_protects_author_or_author_delegate_4ba2a', table='poll_pollvotingtypeforagainst', when='BEFORE')),
        ),
    ]
