# Generated by Django 4.0.8 on 2022-10-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_alter_poll_poll_type_pollproposaltypeschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollproposal',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
