# Generated by Django 4.0.8 on 2023-09-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_alter_group_cover_image_alter_group_image'),
        ('poll', '0010_remove_poll_finished_poll_quorum_poll_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollPrediction',
            new_name='PollPredictionBet',
        ),
    ]
