# Generated by Django 4.2.7 on 2023-12-01 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('poll', '0016_poll_attachments'),
    ]

    operations = [
        migrations.DeleteModel('PollProposalTypeSchedule'),
        migrations.CreateModel(
            name='PollTypeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('poll_type', 3), ('dynamic', True)), _negated=True), name='polltypeisscheduleanddynamic_check'),
        ),
        migrations.AddField(
            model_name='polltypeschedule',
            name='poll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
        migrations.AddField(
            model_name='polltypeschedule',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
        ),
    ]
