# Generated by Django 4.2.7 on 2023-12-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0018_pollproposaltypeschedule_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='poll',
            name='voteenddategreaterthandelegatevoteenddate_check',
        ),
        migrations.RemoveConstraint(
            model_name='poll',
            name='enddategreaterthanvoteenddate_check',
        ),
        migrations.RemoveConstraint(
            model_name='poll',
            name='predictionstatementenddategreaterthanproposalenddate_check',
        ),
        migrations.RemoveConstraint(
            model_name='poll',
            name='delegatevoteenddategreaterthanpredictionbetenddate_check',
        ),
        migrations.RemoveConstraint(
            model_name='poll',
            name='areavoteenddategreaterthanstartdate_check',
        ),
        migrations.RemoveConstraint(
            model_name='poll',
            name='proposalenddategreaterthanareavoteenddate_check',
        ),
        migrations.RemoveConstraint(
            model_name='poll',
            name='predictionbetenddategreaterthanpredictionstatementeneddate_check',
        ),
        migrations.AlterField(
            model_name='poll',
            name='area_vote_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='delegate_vote_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='prediction_bet_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='prediction_statement_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='proposal_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='vote_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('area_vote_end_date__isnull', True), ('area_vote_end_date__gte', models.F('start_date')), _connector='OR')), name='areavoteenddategreaterthanstartdate_check'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('proposal_end_date__isnull', True), ('proposal_end_date__gte', models.F('area_vote_end_date')), _connector='OR')), name='proposalenddategreaterthanareavoteenddate_check'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('prediction_statement_end_date__isnull', True), ('prediction_statement_end_date__gte', models.F('proposal_end_date')), _connector='OR')), name='predictionstatementenddategreaterthanproposalenddate_check'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('prediction_bet_end_date__isnull', True), ('prediction_bet_end_date__gte', models.F('prediction_statement_end_date')), _connector='OR')), name='predictionbetenddategreaterthanpredictionstatementeneddate_check'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('delegate_vote_end_date__isnull', True), ('delegate_vote_end_date__gte', models.F('prediction_bet_end_date')), _connector='OR')), name='delegatevoteenddategreaterthanpredictionbetenddate_check'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('vote_end_date__isnull', True), ('vote_end_date__gte', models.F('delegate_vote_end_date')), _connector='OR')), name='voteenddategreaterthandelegatevoteenddate_check'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('end_date__isnull', True), ('end_date__gte', models.F('vote_end_date')), _connector='OR')), name='enddategreaterthanvoteenddate_check'),
        ),
    ]
