# Generated by Django 4.2.7 on 2024-02-06 16:44

from django.db import migrations, models
import django.db.models.deletion
import flowback.comment.services


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_comment_attachments'),
        ('poll', '0026_pollproposal_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='polldelegatevoting',
            name='comment_section',
            field=models.ForeignKey(default=flowback.comment.services.comment_section_create_model_default, on_delete=django.db.models.deletion.CASCADE, to='comment.commentsection'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='comment_section',
            field=models.ForeignKey(default=flowback.comment.services.comment_section_create_model_default, on_delete=django.db.models.deletion.DO_NOTHING, to='comment.commentsection'),
        ),
    ]
