# Generated by Django 4.2.7 on 2024-02-06 16:34

from django.db import migrations, models
import django.db.models.deletion
import flowback.comment.services


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_comment_attachments'),
        ('poll', '0027_polldelegatevoting_comment_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polldelegatevoting',
            name='comment_section',
            field=models.ForeignKey(default=flowback.comment.services.comment_section_create, on_delete=django.db.models.deletion.CASCADE, to='comment.commentsection'),
        ),
    ]
