# Generated by Django 4.2.7 on 2024-03-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0028_alter_pollvotingtypecardinal_raw_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
