# Generated by Django 4.2.7 on 2024-04-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0029_alter_poll_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polldelegatevoting',
            name='comment_section',
        ),
    ]
