# Generated by Django 4.2.7 on 2024-04-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0030_pollpredictionstatement_combined_bet'),
        ('poll', '0030_remove_polldelegatevoting_comment_section'),
    ]

    operations = [
    ]
