# Generated by Django 4.2.7 on 2024-06-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0033_poll_allow_fast_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='blockchain_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
