# Generated by Django 4.2.7 on 2024-10-07 11:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0040_alter_pollpredictionstatement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollpredictionstatement',
            name='attachments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='group/poll/prediction/attachments'), blank=True, max_length=10, null=True, size=None),
        ),
    ]
