# Generated by Django 4.2.16 on 2025-03-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0042_poll_status_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='work_group_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
