# Generated by Django 4.2.16 on 2025-03-31 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0046_alter_workgroup_chat_and_more'),
        ('poll', '0043_poll_work_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='work_group_id',
        ),
        migrations.AddField(
            model_name='poll',
            name='work_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.workgroup'),
        ),
    ]
