# Generated by Django 4.2.16 on 2025-04-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0044_remove_poll_work_group_id_poll_work_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='interval_mean_absolute_correctness',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
