# Generated by Django 4.2.16 on 2025-04-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0045_poll_interval_mean_absolute_correctness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='interval_mean_absolute_correctness',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Calculates after end date, will contain the current Interval Mean Absolute Correctness at the time of calculation.', max_digits=12, null=True),
        ),
    ]
