# Generated by Django 4.2.17 on 2026-02-05 12:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0060_groupkpi_groupkpivalue'),
        ('poll', '0051_pollpredictionstatement_active_pollproposal_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollProposalKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combined_bet', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('outcome', models.BooleanField(blank=True, default=False, null=True)),
                ('kpi_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupkpivalue')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.pollproposal')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='version',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='PollProposalKPIVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupuser')),
                ('proposal_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.pollproposalkpi')),
            ],
        ),
        migrations.CreateModel(
            name='PollProposalKPIBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupuser')),
                ('proposal_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.pollproposalkpi')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pollproposalkpivote',
            constraint=models.UniqueConstraint(fields=('created_by', 'proposal_kpi'), name='unique_pollproposalkpivote'),
        ),
        migrations.AddConstraint(
            model_name='pollproposalkpibet',
            constraint=models.UniqueConstraint(fields=('created_by', 'proposal_kpi'), name='unique_pollproposalkpibet'),
        ),
        migrations.AddConstraint(
            model_name='pollproposalkpi',
            constraint=models.UniqueConstraint(fields=('proposal', 'kpi_value'), name='unique_pollproposalkpi'),
        ),
    ]
