# Generated by Django 4.2.17 on 2026-02-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0052_pollproposalkpi_poll_version_pollproposalkpivote_and_more'),
        ('poll', '0052_pollproposaltypeschedule_preliminary_score'),
    ]

    operations = [
    ]
