# Generated by Django 4.2.17 on 2026-02-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0053_merge_20260210_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollproposalkpi',
            name='outcome',
        ),
    ]
