# Generated by Django 4.2.30 on 2026-04-30 16:58

import django.core.validators
from django.db import migrations, models


def pre_populate_fields(apps, schema_editor):
    PollProposalKPIBet = apps.get_model('poll', 'pollproposalkpibet')
    for bet in PollProposalKPIBet.objects.all():
        if bet.weight == 0:
            bet.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0054_remove_pollproposalkpi_outcome'),
    ]

    operations = [
        migrations.RunPython(pre_populate_fields),
        migrations.AlterField(
            model_name='pollproposalkpibet',
            name='weight',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
