# Generated by Django 4.2.30 on 2026-05-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0055_alter_pollproposalkpibet_weight'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollvotingtyperanking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pollvotingtyperanking',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pollvotingtyperanking',
            name='author_delegate',
        ),
        migrations.RemoveField(
            model_name='pollvotingtyperanking',
            name='proposal',
        ),
        migrations.RemoveConstraint(
            model_name='poll',
            name='polltypeisscheduleanddynamic_check',
        ),
        migrations.RemoveConstraint(
            model_name='pollphasetemplate',
            name='pollphasetemplatecardinalisvalid_check',
        ),
        migrations.RemoveConstraint(
            model_name='pollphasetemplate',
            name='pollphasetemplatescheduleordynamicisvalid_check',
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('schedule', 'schedule'), ('score', 'score'), ('v2_score', 'v2 score')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pollphasetemplate',
            name='poll_type',
            field=models.CharField(choices=[('schedule', 'schedule'), ('score', 'score'), ('v2_score', 'v2 score')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('poll_type', 'schedule'), ('dynamic', False)), _negated=True), name='polltypeisscheduleanddynamic_check'),
        ),
        migrations.AddConstraint(
            model_name='pollphasetemplate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('poll_type', 'score'), ('poll_is_dynamic', False)), models.Q(models.Q(('area_vote_time_delta__isnull', False), ('proposal_time_delta__isnull', False), ('prediction_statement_time_delta__isnull', False), ('prediction_bet_time_delta__isnull', False), ('delegate_vote_time_delta__isnull', False), ('vote_time_delta__isnull', False), ('end_time_delta__isnull', False), _connector='OR'), _negated=True)), _negated=True), name='pollphasetemplatescoreisvalid_check'),
        ),
        migrations.AddConstraint(
            model_name='pollphasetemplate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('poll_type', 'v2_score'), ('poll_is_dynamic', False)), models.Q(('area_vote_time_delta__isnull', False), ('prediction_statement_time_delta__isnull', False), ('vote_time_delta__isnull', False), ('proposal_time_delta__isnull', True), ('prediction_bet_time_delta__isnull', True), ('delegate_vote_time_delta__isnull', True), ('end_time_delta__isnull', True), _connector='OR')), _negated=True), name='pollphasetemplatev2scoreisvalid_check'),
        ),
        migrations.AddConstraint(
            model_name='pollphasetemplate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('poll_type', 'schedule'), ('poll_is_dynamic', True), _connector='OR'), models.Q(('area_vote_time_delta__isnull', True), ('proposal_time_delta__isnull', True), ('prediction_statement_time_delta__isnull', True), ('prediction_bet_time_delta__isnull', True), ('delegate_vote_time_delta__isnull', True), ('vote_time_delta__isnull', False), ('end_time_delta__isnull', False), _connector='OR')), _negated=True), name='pollphasetemplatescheduleordynamicisvalid_check'),
        ),
        migrations.DeleteModel(
            name='PollVotingTypeRanking',
        ),
    ]
