# Generated by Django 4.0.8 on 2022-12-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationobject',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
