# Generated by Django 4.2.16 on 2025-03-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificationobject_related_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationChannel',
        ),
        migrations.DeleteModel(
            name='NotificationObject',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationSubscription',
        ),
    ]
