# Generated by Django 4.2.16 on 2025-05-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationobject',
            name='notifications',
        ),
        migrations.AlterField(
            model_name='notificationobject',
            name='tag',
            field=models.CharField(help_text='Tag of the notification', max_length=255),
        ),
    ]
