# Generated by Django 4.2.16 on 2025-05-07 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='notification.notificationchannel', verbose_name='parent'),
        ),
    ]
