# Generated by Django 4.2.17 on 2025-10-14 14:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def migrate_notification_subscription_tags(apps, schema_editor):
    """
    Migrate existing NotificationSubscription.tags to NotificationSubscriptionTag model
    """
    NotificationSubscription = apps.get_model('notification', 'NotificationSubscription')
    NotificationSubscriptionTag = apps.get_model('notification', 'NotificationSubscriptionTag')
    
    # Get all subscriptions with tags
    subscriptions_with_tags = NotificationSubscription.objects.filter(tags__isnull=False)
    
    # Create NotificationSubscriptionTag records for each tag
    subscription_tags_to_create = []
    for subscription in subscriptions_with_tags:
        for tag in subscription.tags:
            subscription_tags_to_create.append(
                NotificationSubscriptionTag(
                    subscription=subscription,
                    name=tag,
                    reminders=None  # Default reminders as None
                )
            )

    # Bulk create all subscription tags
    if subscription_tags_to_create:
        NotificationSubscriptionTag.objects.bulk_create(subscription_tags_to_create)


def reverse_migrate_notification_subscription_tags(apps, schema_editor):
    """
    Reverse migration: move NotificationSubscriptionTag back to NotificationSubscription.tags
    """
    NotificationSubscription = apps.get_model('notification', 'NotificationSubscription')
    NotificationSubscriptionTag = apps.get_model('notification', 'NotificationSubscriptionTag')
    
    # Group subscription tags by subscription
    for subscription in NotificationSubscription.objects.all():
        subscription_tags = NotificationSubscriptionTag.objects.filter(subscription=subscription)
        tag_names = [tag.name for tag in subscription_tags]
        
        # Update the subscription with the tag names
        if tag_names:
            subscription.tags = tag_names
            subscription.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0008_fix_imagefield_in_notification_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notification',
            name='reminder',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user', 'notification_object', 'reminder')},
        ),
        migrations.CreateModel(
            name='NotificationSubscriptionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('reminders', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='Reminder times for the given tag', null=True, size=None)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notificationsubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(
            migrate_notification_subscription_tags,
            reverse_migrate_notification_subscription_tags
        ),
        migrations.RemoveField(
            model_name='notificationsubscription',
            name='tags',
        ),
    ]
