# Generated by Django 4.0.3 on 2022-09-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuserdelegate',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupuserdelegatepool'),
        ),
    ]
