# Generated by Django 4.0.3 on 2022-08-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupuserinvite',
            name='external',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
