# Generated by Django 4.0.3 on 2022-08-11 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_grouptags_groupuser_group_groupuser_is_delegate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupuserdelegate',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tags',
        ),
        migrations.AddField(
            model_name='grouptags',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grouptags',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='grouptags',
            unique_together={('tag_name', 'group')},
        ),
    ]
