# Generated by Django 4.0.3 on 2022-10-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_groupuserdelegate_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupuserdelegate',
            old_name='user',
            new_name='group_user',
        ),
        migrations.AlterUniqueTogether(
            name='groupuserdelegate',
            unique_together={('group_user', 'group')},
        ),
    ]
