# Generated by Django 4.0.3 on 2022-08-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_rename_tag_groupuserdelegate_tags_remove_group_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grouptags',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
