# Generated by Django 4.0.8 on 2022-11-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_rename_user_groupuserdelegate_group_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='hide_poll_users',
            field=models.BooleanField(default=False),
        ),
    ]
