# Generated by Django 4.0.3 on 2022-08-30 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_groupuserdelegate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='jitsi_room',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
