# Generated by Django 4.0.3 on 2022-08-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_groupuser_is_admin_alter_grouptags_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='banner_description',
        ),
    ]
