# Generated by Django 4.0.3 on 2022-08-31 13:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0005_alter_group_jitsi_room'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupuserinvite',
            unique_together={('user', 'group')},
        ),
    ]
