# Generated by Django 4.0.8 on 2023-02-13 15:30

from django.db import migrations, models
import django.db.models.deletion


def pre_populate_fields(apps, schema_editor):
    Group = apps.get_model('group', 'group')
    Schedule = apps.get_model('schedule', 'schedule')
    for group in Group.objects.all():
        schedule = Schedule.objects.create(name=group.name, origin_name='group', origin_id=group.id)
        group.schedule_id = schedule.id
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('group', '0007_alter_grouppermissions_create_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
            preserve_default=False,
        ),
        migrations.RunPython(pre_populate_fields),
        migrations.AlterField(
            model_name='group',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')
        )
    ]
