# Generated by Django 4.0.8 on 2023-02-27 14:45

from django.db import migrations, models
import django.db.models.deletion


def pre_populate_fields(apps, schema_editor):
    Group = apps.get_model('group', 'group')
    User = apps.get_model('user', 'user')
    Kanban = apps.get_model('kanban', 'kanban')
    KanbanSubscription = apps.get_model('kanban', 'kanbansubscription')

    # Register groups to kanban, Kanban already generates some existing group kanbans
    for group in Group.objects.all():
        kanban, created = Kanban.objects.get_or_create(origin_type='group',
                                                       origin_id=group.id,
                                                       defaults=dict(name=group.name))
        group.kanban_id = kanban.id
        group.save()

    # Iterate trough users to subscribe them to group kanbans
    for user in User.objects.all():
        for group in Group.objects.filter(groupuser__user=user).all():
            KanbanSubscription.objects.create(kanban=user.kanban, target=group.kanban)


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_kanban_alter_kanbanentry_assignee_and_more'),
        ('user', '0004_user_kanban'),
        ('group', '0010_alter_group_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='kanban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanban.kanban'),
        ),
        migrations.RunPython(pre_populate_fields)
    ]
