# Generated by Django 4.0.8 on 2023-05-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_group_kanban'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermissions',
            name='force_delete_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='force_delete_poll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='force_delete_proposal',
            field=models.BooleanField(default=False),
        ),
    ]
