# Generated by Django 4.0.8 on 2023-05-22 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import flowback.comment.models
import flowback.comment.services


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_active'),
        ('group', '0012_grouppermissions_force_delete_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('comment_section', models.ForeignKey(default=flowback.comment.models.comment_section_create, on_delete=django.db.models.deletion.DO_NOTHING, to='comment.commentsection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
