# Generated by Django 4.0.8 on 2023-06-02 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_groupthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='default_quorum',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='create_proposal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='delete_proposal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='poll_quorum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='update_proposal',
            field=models.BooleanField(default=True),
        ),
    ]
