# Generated by Django 4.0.8 on 2023-10-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_alter_group_cover_image_alter_group_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouptags',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='grouptags',
            unique_together={('name', 'group')},
        ),
    ]
