# Generated by Django 4.2.7 on 2023-11-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0016_rename_tag_name_grouptags_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
