# Generated by Django 4.2.7 on 2023-11-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0017_groupuser_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupthread',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
