# Generated by Django 4.2.7 on 2023-12-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0019_groupfolder_group_group_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermissions',
            name='create_kanban_task',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='delete_kanban_task',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='update_kanban_task',
            field=models.BooleanField(default=True),
        ),
    ]
