# Generated by Django 4.2.7 on 2024-01-24 14:09

from django.db import migrations, models
import django.db.models.deletion


def create_group_chat(apps, schema_editor):
    Group = apps.get_model("group", "Group")
    MessageChannel = apps.get_model("chat", "MessageChannel")

    for group in Group.objects.all():
        group.chat = MessageChannel.objects.create(origin_name="group")
        group.save()


class Migration(migrations.Migration):
    dependencies = [
        ('schedule', '0001_initial'),
        ('chat', '0004_message_messagechannel_messagechannelparticipant_and_more'),
        ('kanban', '0004_kanbanentry_priority'),
        ('group', '0020_grouppermissions_create_kanban_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.messagechannel')
        ),
        migrations.RunPython(create_group_chat),
        migrations.AlterField(
            model_name='group',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.messagechannel')
        ),
        migrations.AlterField(
            model_name='group',
            name='kanban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='kanban.kanban'),
        ),
        migrations.AlterField(
            model_name='group',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='schedule.schedule'),
        ),
    ]
