# Generated by Django 4.2.7 on 2024-03-07 16:36

from django.db import migrations, models
import django.db.models.deletion


def generate_channel_participants(apps, schema_editor):
    GroupUser = apps.get_model("group", "GroupUser")
    MessageChannelParticipant = apps.get_model("chat", "MessageChannelParticipant")

    for group_user in GroupUser.objects.all():
        group_user.chat_participant = MessageChannelParticipant.objects.create(user=group_user.user,
                                                                               channel=group_user.group.chat)
        group_user.save()




class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0007_messagechannelparticipant_active'),
        ('group', '0022_alter_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupuser',
            name='chat_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='chat.messagechannelparticipant', null=True, blank=True),
            preserve_default=False,
        ),
        migrations.RunPython(generate_channel_participants)
    ]
