# Generated by Django 4.2.7 on 2024-03-07 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_messagechannelparticipant_active'),
        ('group', '0023_groupuser_chat_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuser',
            name='chat_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.messagechannelparticipant'),
        ),
    ]
