# Generated by Django 4.2.7 on 2024-04-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0025_groupuserdelegatepool_comment_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermissions',
            name='poll_fast_forward',
            field=models.BooleanField(default=False),
        ),
    ]
