# Generated by Django 4.2.7 on 2024-05-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0026_grouppermissions_poll_fast_forward'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(check=models.Q(('public', True), ('direct_join', True), _connector='OR'), name='group_not_private_and_direct_join_check'),
        ),
    ]
