# Generated by Django 4.2.7 on 2024-05-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0029_remove_group_group_not_private_and_direct_join_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='direct_join',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
