# Generated by Django 4.2.7 on 2024-07-24 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0034_remove_grouppermissions_prediction_statement_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupThreadVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupuser')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupthread')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
