# Generated by Django 4.2.7 on 2024-07-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0035_groupthreadvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupthread',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
