# Generated by Django 4.2.7 on 2024-08-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0036_groupthread_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermissions',
            name='allow_delegate',
            field=models.BooleanField(default=True),
        ),
    ]
