# Generated by Django 4.2.7 on 2024-09-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0038_workgroup_workgroupuserjoinrequest_workgroupuser'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workgroupuser',
            constraint=models.UniqueConstraint(fields=('work_group', 'group_user'), name='WorkGroupUser_group_user_and_work_group_is_unique'),
        ),
        migrations.AddConstraint(
            model_name='workgroupuserjoinrequest',
            constraint=models.UniqueConstraint(fields=('work_group', 'group_user'), name='WorkGroupUserJoinRequest_group_user_and_work_group_is_unique'),
        ),
    ]
