# Generated by Django 4.2.7 on 2024-11-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0039_workgroupuser_workgroupuser_group_user_and_work_group_is_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='poll_phase_minimum_space',
            field=models.IntegerField(default=0),
        ),
    ]
