# Generated by Django 4.2.7 on 2024-11-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0040_group_poll_phase_minimum_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermissions',
            name='send_group_email',
            field=models.BooleanField(default=False),
        ),
    ]
