# Generated by Django 4.2.16 on 2025-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0042_alter_group_blockchain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptags',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
