# Generated by Django 4.2.16 on 2025-03-06 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0043_grouptags_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupthread',
            name='work_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.workgroup'),
        ),
    ]
