# Generated by Django 4.2.16 on 2025-03-10 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_messagechannel_users'),
        ('group', '0045_workgroup_chat_workgroupuser_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.messagechannel'),
        ),
        migrations.AlterField(
            model_name='workgroupuser',
            name='chat_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.messagechannelparticipant'),
        ),
    ]
