# Generated by Django 4.2.17 on 2025-08-26 11:06

from django.db import migrations, models
import django.db.models.deletion
import flowback.group.models


def set_group_users_default_permissions_and_chat_titles(apps, schema_editor):
    """Set every GroupUser's permission to their group's default permission."""
    Group = apps.get_model('group', 'Group')
    GroupPermissions = apps.get_model('group', 'GroupPermissions')

    for group in Group.objects.filter(default_permission=None).all():
        group.default_permission = GroupPermissions.objects.create(author=group)
        group.chat.title = group.name
        group.chat.save()
        group.save()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('group', '0049_alter_groupthread_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermissions',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='group.group'),
        ),
        migrations.RunPython(set_group_users_default_permissions_and_chat_titles),
        migrations.AlterField(
            model_name='group',
            name='default_permission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='group.grouppermissions'),
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='group.grouppermissions',
                                    null=True),
        ),
    ]
