# Generated by Django 4.2.17 on 2025-08-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0050_alter_group_default_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermissions',
            name='role_name',
            field=models.TextField(default='default'),
        ),
    ]
