# Generated by Django 4.2.17 on 2025-08-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0051_alter_grouppermissions_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuser',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.grouppermissions'),
        ),
    ]
