# Generated by Django 4.2.17 on 2026-02-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0060_groupkpi_groupkpivalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupkpivalue',
            name='value',
            field=models.CharField(),
        ),
    ]
