# Generated by Django 4.2.17 on 2026-03-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0061_alter_groupkpivalue_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='blockchain_id',
            field=models.PositiveIntegerField(blank=True, help_text='User-Defined Blockchain ID', null=True, unique=True),
        ),
    ]
