# Generated by Django 4.2.6 on 2023-10-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='attachments',
        ),
    ]
