# Generated by Django 4.2.7 on 2024-05-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_comment_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(check=models.Q(('attachments__isnull', False), ('message__isnull', False), _connector='OR'), name='comment_data_check'),
        ),
    ]
