# Generated by Django 4.2.7 on 2024-05-24 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filesegment_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0006_alter_comment_message_comment_comment_data_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, max_length=10000, null=True)),
                ('active', models.BooleanField(default=True)),
                ('score', models.IntegerField(default=0)),
                ('attachments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.filecollection')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.commentsection')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comment.tempcomment', verbose_name='parent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
