# Generated by Django 4.2.7 on 2024-06-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_tempcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcomment',
            name='score',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=17),
        ),
    ]
