# Generated by Django 4.2.7 on 2024-06-04 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_commentvote_alter_tempcomment_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempcomment',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='tempcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tempcomment',
            name='comment_section',
        ),
        migrations.RemoveField(
            model_name='tempcomment',
            name='parent',
        ),
        migrations.RemoveConstraint(
            model_name='comment',
            name='comment_data_check',
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comment.comment', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(check=models.Q(('attachments__isnull', False), ('message__isnull', False), _connector='OR'), name='temp_comment_data_check'),
        ),
        migrations.DeleteModel(
            name='TempComment',
        ),
    ]
