# Generated by Django 4.2.7 on 2024-06-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0010_remove_tempcomment_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=17),
        ),
    ]
