# Generated by Django 4.0.8 on 2022-11-15 16:25

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_remove_poll_nowgreaterthanstartdate_check'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='poll',
            name='proposalenddategreaterthanstartdate_check',
        ),
        migrations.RemoveConstraint(
            model_name='poll',
            name='predictionenddategreaterthanproposalenddate_check',
        ),
        migrations.RemoveConstraint(
            model_name='poll',
            name='delegatevoteenddategreaterthanpredictionenddate_check',
        ),
        migrations.RemoveConstraint(
            model_name='poll',
            name='voteenddategreaterthandelegatevoteenddate_check',
        ),
        migrations.RemoveConstraint(
            model_name='poll',
            name='enddategreaterthanvoteenddate_check',
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(('proposal_end_date__gt', django.db.models.expressions.F('start_date'))), name='proposalenddategreaterthanstartdate_check'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(('prediction_end_date__gt', django.db.models.expressions.F('proposal_end_date'))), name='predictionenddategreaterthanproposalenddate_check'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(('delegate_vote_end_date__gt', django.db.models.expressions.F('prediction_end_date'))), name='delegatevoteenddategreaterthanpredictionenddate_check'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(('vote_end_date__gt', django.db.models.expressions.F('delegate_vote_end_date'))), name='voteenddategreaterthandelegatevoteenddate_check'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', django.db.models.expressions.F('vote_end_date'))), name='enddategreaterthanvoteenddate_check'),
        ),
    ]
