# Generated by Django 4.0.8 on 2023-04-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_pollprediction_pollpredictionstatement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
