# Generated by Django 4.0.8 on 2023-09-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_alter_group_cover_image_alter_group_image'),
        ('poll', '0011_rename_pollprediction_pollpredictionbet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollpredictionbet',
            unique_together={('prediction_statement', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='pollpredictionstatementvote',
            unique_together={('prediction_statement', 'created_by')},
        ),
    ]
