# Generated by Django 4.0.8 on 2023-09-22 10:01

from django.db import migrations, models
import django.db.models.expressions


def pre_populate_fields(apps, schema_editor):
    Poll = apps.get_model('poll', 'poll')
    polls = []

    for poll in Poll.objects.all():
        poll.prediction_statement_end_date = poll.proposal_end_date
        poll.area_vote_end_date = poll.proposal_end_date
        poll.prediction_bet_end_date = poll.proposal_end_date
        polls.append(poll)

    Poll.objects.bulk_update(polls, ['prediction_statement_end_date', 'area_vote_end_date', 'prediction_bet_end_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_alter_pollpredictionbet_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='poll',
            name='votestartdategreaterthanproposalenddate_check',
        ),
        migrations.RemoveConstraint(
            model_name='poll',
            name='delegatevoteenddategreaterthanvotestartdate_check',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='vote_start_date',
        ),
        migrations.AddField(
            model_name='poll',
            name='area_vote_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='prediction_bet_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='prediction_statement_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(('prediction_statement_end_date__gte', django.db.models.expressions.F('proposal_end_date'))), name='predictionstatementenddategreaterthanproposalenddate_check'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(('area_vote_end_date__gte', django.db.models.expressions.F('prediction_statement_end_date'))), name='areavoteenddategreaterthanpredictionstatementenddate_check'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(('prediction_bet_end_date__gte', django.db.models.expressions.F('area_vote_end_date'))), name='predictionbetenddategreaterthanareavoteenddate_check'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(('delegate_vote_end_date__gte', django.db.models.expressions.F('prediction_bet_end_date'))), name='delegatevoteenddategreaterthanpredictionbetenddate_check'),
        ),
        migrations.RunPython(pre_populate_fields),
        migrations.AlterField(
            model_name='poll',
            name='area_vote_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='prediction_bet_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='prediction_statement_end_date',
            field=models.DateTimeField(),
        ),
    ]
