# Generated by Django 4.2.7 on 2023-11-02 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('poll', '0015_pollareastatement_pollareastatementsegment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='attachments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.filecollection'),
        ),
    ]
