# Generated by Django 4.2.7 on 2023-12-01 14:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('poll', '0017_polltypeschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollProposalTypeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleevent')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poll.pollproposal')),
            ],
        )
    ]
