# Generated by Django 4.2.7 on 2023-12-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0019_remove_poll_voteenddategreaterthandelegatevoteenddate_check_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='poll',
            name='polltypeisscheduleanddynamic_check',
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('poll_type', 3), ('dynamic', False)), _negated=True), name='polltypeisscheduleanddynamic_check'),
        ),
    ]
