# Generated by Django 4.2.7 on 2023-12-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0020_remove_poll_polltypeisscheduleanddynamic_check_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollvotingtypecardinal',
            old_name='score',
            new_name='raw_score',
        ),
    ]
