# Generated by Django 4.2.7 on 2023-12-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0023_alter_pollvotingtypecardinal_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollvotingtypecardinal',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
