# Generated by Django 4.2.7 on 2023-12-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0024_alter_pollvotingtypecardinal_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='polldelegatevoting',
            name='mandate',
            field=models.IntegerField(default=0),
        ),
    ]
