# Generated by Django 4.2.7 on 2024-01-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filesegment_name'),
        ('poll', '0025_polldelegatevoting_mandate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollproposal',
            name='attachments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.filecollection'),
        ),
    ]
