# Generated by Django 4.2.7 on 2024-02-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0027_polldelegatevoting_comment_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollvotingtypecardinal',
            name='raw_score',
            field=models.IntegerField(default=0),
        ),
    ]
