# Generated by Django 4.2.7 on 2024-04-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0031_merge_20240411_1936'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pollproposaltypeschedule',
            constraint=models.UniqueConstraint(fields=('proposal', 'event'), name='unique_proposaltypeschedule'),
        ),
    ]
