# Generated by Django 4.2.7 on 2024-06-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0034_poll_blockchain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollpredictionstatement',
            name='blockchain_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pollproposal',
            name='blockchain_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
