# Generated by Django 4.2.7 on 2024-06-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0036_pollpredictionbet_blockchain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollpredictionbet',
            name='blockchain_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
