# Generated by Django 4.2.7 on 2024-08-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0038_pollphasetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollpredictionstatement',
            name='title',
            field=models.CharField(default="Untitled", max_length=255),
            preserve_default=False,
        ),
    ]
