# Generated by Django 4.0.8 on 2023-02-22 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def pre_populate_fields(apps, schema_editor):
    Kanban = apps.get_model('kanban', 'kanban')
    KanbanEntry = apps.get_model('kanban', 'kanbanentry')
    GroupUser = apps.get_model('group', 'groupuser')
    for entry in KanbanEntry.objects.all():
        group_user = GroupUser.objects.get(id=entry.created_by)
        kanban, created = Kanban.objects.get_or_create(name=group_user.group.name,
                                                       defaults=dict(origin_type='group',
                                                                     origin_id=group_user.group.id))
        entry.kanban = kanban

        if entry.assignee == entry.created_by:
            entry.assignee = None

        else:
            assignee = GroupUser.objects.get(id=entry.assignee).user
            entry.assignee = assignee.id

        entry.created_by = group_user.user.id

        entry.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('origin_type', models.CharField(max_length=255)),
                ('origin_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('origin_type', 'origin_id')},
            },
        ),
        migrations.AlterField(
            model_name='kanbanentry',
            name='assignee',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='kanbanentry',
            name='created_by',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='kanbanentry',
            name='kanban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='kanban.kanban'),
        ),
        migrations.RunPython(pre_populate_fields),
        migrations.AlterField(
            model_name='kanbanentry',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_entry_assignee',
                                    to=settings.AUTH_USER_MODEL, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='kanbanentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_entry_created_by',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kanbanentry',
            name='kanban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='kanban.kanban'),
        ),
        migrations.CreateModel(
            name='KanbanSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kanban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='kanban_subscription_kanban', to='kanban.kanban')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='kanban_subscription_target', to='kanban.kanban')),
            ],
            options={
                'unique_together': {('kanban', 'target')},
            },
        ),
    ]
