# Generated by Django 4.0.8 on 2023-04-12 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_kanbanentry_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanentry',
            name='priority',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
