# Generated by Django 4.2.7 on 2024-07-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filesegment_name'),
        ('kanban', '0005_alter_kanbanentry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanentry',
            name='attachments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.filecollection'),
        ),
    ]
