# Generated by Django 4.2.7 on 2024-09-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0038_workgroup_workgroupuserjoinrequest_workgroupuser'),
        ('kanban', '0007_kanbanentry_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanbanentry',
            name='category',
        ),
        migrations.AddField(
            model_name='kanbanentry',
            name='work_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.workgroup'),
        ),
    ]
