# Generated by Django 4.2.16 on 2024-11-21 13:29

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0008_remove_kanbanentry_category_kanbanentry_work_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanEntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='kanbanentry',
            name='tag',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='kanbanentry',
            old_name='tag',
            new_name='lane',
        ),
        migrations.AlterField(
            model_name='kanbanentry',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
