# Generated by Django 3.1.2 on 2022-03-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directmessage',
            unique_together=set(),
        ),
    ]
