# Generated by Django 4.0.8 on 2023-02-06 14:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_groupmessageuserdata_directmessageuserdata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directmessageuserdata',
            unique_together={('user', 'target')},
        ),
    ]
