# Generated by Django 4.2.7 on 2024-02-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messagechanneltopic_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechannelparticipant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
