# Generated by Django 4.2.7 on 2024-10-01 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_messagechannelparticipant_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechannel',
            name='users',
            field=models.ManyToManyField(through='chat.MessageChannelParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
