# Generated by Django 4.2.16 on 2025-03-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_messagechannel_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default='message', max_length=255),
        ),
    ]
